apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store-front
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: store-front=357229909289.dkr.ecr.us-east-1.amazonaws.com/dsop/store-front
    argocd-image-updater.argoproj.io/store-front.update-strategy: semver
    argocd-image-updater.argoproj.io/store-front.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+-.+$
    argocd-image-updater.argoproj.io/store-front.ignore-tags: latest, dev, staging
    argocd-image-updater.argoproj.io/write-back-method: argocd
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-notifications
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd-notifications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: store-front
    app.kubernetes.io/part-of: store-app
    deployment-strategy: blue-green
spec:
  project: default
  source:
    repoURL: https://github.com/prasad-moru/dsop-project.git
    targetRevision: main
    path: helm-charts/store-front
    helm:
      releaseName: store-front
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  ignoreDifferences:
    - group: argoproj.io
      kind: AnalysisTemplate
      jsonPointers:
        - /spec/metrics
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/template/metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10