# version: "3.7"
services:
  ai-service:
    build: ../ai-service
    container_name: ai-service
    restart: always
    ports:
      - 5001:5001
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://ai-service:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - USE_AZURE_OPENAI=False
      - USE_LOCAL_LLM=False
      - OPENAI_API_KEY=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         # ✅ fill this in - required!
      - OPENAI_ORG_ID=org-MQENs1E0HzS2Bg6rgEc4jkR6     # ✅ already filled - good
      - OPENAI_IMAGE_MODEL=dall-e-3     # ✅ add this - change to gpt-image-1 in May
    networks:
      - backend_services
networks:
  backend_services:
    driver: bridge